
//get categories
export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

//get categoryById
export const FETCH_CATEGORIESBYID_START = "FETCH_CATEGORIESBYID_START";
export const FETCH_CATEGORIESBYID_SUCCESS = "FETCH_CATEGORIESBYID_SUCCESS";
export const FETCH_CATEGORIESBYID_FAIL = "FETCH_CATEGORIESBYID_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";

export const REDIRECT_PATH = "REDIRECT_PATH"

//register seller
export const ADD_SELLER_INFO = "ADD_SELLER_INFO"
export const SELLER_REGISTER_SUCCESS = "SELLER_REGISTER_SUCCESS"
export const SELLER_REGISTER_FAIL = "SELLER_REGISTER_FAIL"
export const SELLER_REGISTER_START = "SELLER_REGISTER_START"

